using UTCGP
import SearchNetworks as sn
using DataStructures
import UTCGP: _unique_names_in_bundle, get_sr_float_bundles
import UTCGP: SImageND
import TestImages: testimage
import ImageSegmentation
using ImageCore
using ImageMorphology
using ImageFiltering
using Statistics
using ErrorTypes

const USING_RETEST = isdefined(@__MODULE__, :ReTest)

include("element_nodes/test_element_node.jl")
include("element_nodes/test_random_from_node_element.jl")
include("nodes/test_nodes.jl")
include("nodes/test_make_nodes.jl")
include("genome/test_make_single_genome.jl")
include("genome/test_diff_seed.jl")
include("hash/hash_genome_test.jl")
include("config/config.jl")
include("meta_library/test_library.jl")
include("meta_library/test_meta_library.jl")
include("libraries/clone_bundle.jl")
include("programs/test_build_program.jl")
include("programs/test_decode_program.jl")
include("mutations/test_utils_mutations.jl")
include("mutations/test_standard_mutation.jl")
include("mutations/test_numbered_mutation.jl")
include("fitters/test_default_mutation.jl")
include("fitters/test_ga.jl")
include("endpoints/test_levenshtein.jl")
include("libraries/casters.jl")
include("libraries/string/grep.jl")
include("libraries/string/test_grep.jl")
include("libraries/string/paste.jl")
include("libraries/string/test_conditional.jl")
include("libraries/string/test_caps.jl")
include("libraries/string/test_basic.jl")
include("libraries/string/test_parse.jl")
include("libraries/list_generic/test_basic.jl")
include("libraries/list_generic/test_make_lists.jl")
include("libraries/list_generic/test_concat.jl")
include("libraries/list_generic/test_subset.jl")
include("libraries/list_generic/test_set.jl")
include("libraries/list_generic/test_where.jl")
include("libraries/list_generic/test_utils.jl")
include("libraries/list_number/test_arithmetic.jl")
include("libraries/list_number/test_algebraic.jl")
include("libraries/list_number/test_recursive.jl")
include("libraries/list_number/test_vectuples.jl")
include("libraries/list_number/test_basic.jl")
include("libraries/list_integer/test_iscond.jl")
include("libraries/list_integer/test_string.jl")
include("libraries/list_integer/test_primes.jl")
include("libraries/list_string/test_split.jl")
include("libraries/list_string/test_caps.jl")
include("libraries/list_string/test_broadcast.jl")
include("libraries/list_tuple/test_list_tuple_combinatorics.jl")
include("libraries/list_tuple/test_list_tuple_mappings.jl")
include("libraries/element/test_vector_interface.jl")
include("libraries/element/test_conditional.jl")
include("libraries/number/test_arithmetic.jl")
include("libraries/number/test_reduce.jl")
include("libraries/number/test_transcendental.jl")
include("libraries/number/test_reduce_from_img.jl")
include("images/pool_tests.jl")
include("images/pooler_tests.jl")
include("libraries/bool/test_basic.jl")
include("libraries/test_modular_functions.jl")
include("libraries/image2D/tests_image2D.jl")
include("libraries/image2D/test_basic_image2D.jl")
include("libraries/image2D/test_morph_image2D.jl")
include("libraries/image2D/test_binarize_image2D.jl")
include("libraries/image2D/test_segmentation_image2D.jl")
include("libraries/image2D/test_arithmetic_image2D.jl")
include("libraries/image2D/test_barithmetic_image2D.jl")
include("libraries/image2D/test_transcendental_image2D.jl")
include("libraries/image2D/test_filtering_image2D.jl")
include("libraries/integer/test_basic.jl")
include("libraries/integer/test_find.jl")
include("libraries/integer/test_modulo.jl")
include("libraries/integer/test_cond.jl")
include("problem_specific/test_basement.jl")
include("problem_specific/test_bouncing_balls.jl")
include("problem_specific/test_camel_case.jl")
include("problem_specific/test_coin_sums.jl")
include("problem_specific/test_cut_vector.jl")
include("problem_specific/test_dice_game.jl")
include("problem_specific/test_find_pair.jl")
include("problem_specific/test_fizz_buzz.jl")
include("problem_specific/test_fuel_cost.jl")
include("problem_specific/test_gcd.jl")
include("problem_specific/test_indices_of_substring.jl")
include("problem_specific/test_leaders.jl")
include("problem_specific/test_luhn.jl")
include("problem_specific/test_mastermind.jl")
include("problem_specific/test_middle_character.jl")
include("problem_specific/test_paired_digits.jl")
include("problem_specific/test_shopping_list.jl")
include("problem_specific/test_snow_day.jl")
include("problem_specific/test_solve_booleans.jl")
include("problem_specific/test_spin_words.jl")
include("problem_specific/test_square_digits.jl")
include("problem_specific/test_substitution_cipher.jl")
include("problem_specific/test_twitter.jl")
include("problem_specific/test_vec_dist.jl")
include("search_network/test_sn_writer_init_utils.jl")
include("search_network/test_writer_internals.jl")
include("search_network/test_hashers.jl")
include("search_network/test_node_hashers.jl")
include("search_network/writer_instantiation.jl")
include("search_network/test_behavior_hasher.jl")
include("search_network/test_phen_hasher.jl")
include("search_network/test_edge_props.jl")
include("search_network/sn_test.jl")
