name = "UTCGP"
uuid = "956831e1-0a7a-492a-ae16-058c6128a9f2"
authors = ["Camilo De La Torre <camilo.de-la-torre@ut-capitole.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
